services:
  db:
    image: postgres:16
    container_name: security_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: musicdb
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: supersecretpassword123
    ports:
      - "5432:5432"
    volumes:
      - security_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musicuser -d musicdb"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  security_data:
